// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Desenvolvedor",
            "email": "contato@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/download-qrcode": {
            "get": {
                "description": "Faz o download de um QR code para o código PIX gerado, opcionalmente aplicando um template",
                "produces": [
                    "image/png",
                    "application/json"
                ],
                "tags": [
                    "pix"
                ],
                "summary": "Download QR Code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código PIX gerado",
                        "name": "codigo_pix",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Formato de resposta (json ou png, padrão é png)",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nome do template a ser aplicado (ex: template_pix_1)",
                        "name": "template",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalhes do QR Code em JSON",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.PixResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Código PIX não fornecido",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    },
                    "404": {
                        "description": "Código PIX não encontrado",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    }
                }
            }
        },
        "/generate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gera um novo código PIX estático com base nos dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pix"
                ],
                "summary": "Gerar código PIX",
                "parameters": [
                    {
                        "description": "Dados para geração do PIX",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.PixRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código PIX gerado com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.PixResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Erro de requisição",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    },
                    "401": {
                        "description": "Não autorizado",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica um estabelecimento e retorna um token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticacao"
                ],
                "summary": "Login de estabelecimento",
                "parameters": [
                    {
                        "description": "Credenciais de login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login realizado com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Erro de validação dos dados",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    },
                    "401": {
                        "description": "Credenciais inválidas",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    }
                }
            }
        },
        "/registrar": {
            "post": {
                "description": "Registra um novo estabelecimento no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "autenticacao"
                ],
                "summary": "Registrar estabelecimento",
                "parameters": [
                    {
                        "description": "Dados do estabelecimento",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.EstabelecimentoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Estabelecimento criado com sucesso",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.EstabelecimentoResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Erro de validação dos dados",
                        "schema": {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rodrigocostarcs_pix-generator_internal_domain_models.EstabelecimentoRequest": {
            "type": "object",
            "required": [
                "email",
                "nome",
                "senha"
            ],
            "properties": {
                "descricao": {
                    "description": "Descrição do estabelecimento (opcional)\nexample: Loja de produtos diversos",
                    "type": "string"
                },
                "email": {
                    "description": "Email do estabelecimento (usado para login)\nrequired: true\nexample: contato@lojadojose.com.br",
                    "type": "string"
                },
                "nome": {
                    "description": "Nome do estabelecimento\nrequired: true\nexample: Loja do José",
                    "type": "string"
                },
                "senha": {
                    "description": "Senha do estabelecimento (mínimo 6 caracteres)\nrequired: true\nexample: senha123\nmin length: 6",
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "github_com_rodrigocostarcs_pix-generator_internal_domain_models.EstabelecimentoResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "description": "Status de ativação do estabelecimento\nexample: true",
                    "type": "boolean"
                },
                "atualizado_em": {
                    "description": "Data da última atualização\nexample: 2023-01-01T12:00:00Z",
                    "type": "string"
                },
                "criado_em": {
                    "description": "Data de criação\nexample: 2023-01-01T12:00:00Z",
                    "type": "string"
                },
                "descricao": {
                    "description": "Descrição do estabelecimento (opcional)\nexample: Loja de produtos diversos",
                    "type": "string"
                },
                "email": {
                    "description": "Email do estabelecimento\nexample: contato@lojadojose.com.br",
                    "type": "string"
                },
                "id": {
                    "description": "ID único do estabelecimento\nexample: 123e4567-e89b-12d3-a456-426614174000",
                    "type": "string"
                },
                "nome": {
                    "description": "Nome do estabelecimento\nexample: Loja do José",
                    "type": "string"
                }
            }
        },
        "github_com_rodrigocostarcs_pix-generator_internal_domain_models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "senha"
            ],
            "properties": {
                "email": {
                    "description": "Email do estabelecimento\nrequired: true\nexample: contato@lojadojose.com.br",
                    "type": "string"
                },
                "senha": {
                    "description": "Senha do estabelecimento\nrequired: true\nexample: senha123",
                    "type": "string"
                }
            }
        },
        "github_com_rodrigocostarcs_pix-generator_internal_domain_models.LoginResponse": {
            "type": "object",
            "properties": {
                "estabelecimento": {
                    "description": "Informações do estabelecimento autenticado",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_rodrigocostarcs_pix-generator_internal_domain_models.EstabelecimentoResponse"
                        }
                    ]
                },
                "token": {
                    "description": "Token JWT para autenticação nas rotas protegidas\nexample: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                    "type": "string"
                }
            }
        },
        "github_com_rodrigocostarcs_pix-generator_internal_domain_models.PixRequest": {
            "type": "object",
            "required": [
                "chave",
                "cidade",
                "nome"
            ],
            "properties": {
                "chave": {
                    "description": "Chave PIX do beneficiário (obrigatório)\nrequired: true\nexample: josesilva@email.com",
                    "type": "string"
                },
                "cidade": {
                    "description": "Cidade do beneficiário (obrigatório)\nrequired: true\nexample: SAO PAULO",
                    "type": "string"
                },
                "descricao": {
                    "description": "Descrição da transação (opcional)\nexample: PAGAMENTO DE SERVICOS",
                    "type": "string"
                },
                "identificador": {
                    "description": "Identificador único da transação (opcional)\nexample: FATURA123",
                    "type": "string"
                },
                "nome": {
                    "description": "Nome do beneficiário do PIX (obrigatório)\nrequired: true\nexample: JOSE DA SILVA",
                    "type": "string"
                },
                "valor": {
                    "description": "Valor da transação (opcional)\nexample: 100.50",
                    "type": "number"
                }
            }
        },
        "github_com_rodrigocostarcs_pix-generator_internal_domain_models.PixResponse": {
            "type": "object",
            "properties": {
                "codigo_pix": {
                    "description": "Código PIX gerado conforme padrão EMV\nexample: 00020101021126580014BR.GOV.BCB.PIX0136josesilva@email.com5204000053039865802BR5913JOSE DA SILVA6009SAO PAULO62150511FATURA12308103100.506304E5B1",
                    "type": "string"
                },
                "qrcode_png": {
                    "description": "QR Code em formato PNG (base64)\nexample: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...",
                    "type": "string"
                },
                "qrcode_svg": {
                    "description": "QR Code em formato SVG\nexample: \u003csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 250 250'\u003e...\u003c/svg\u003e",
                    "type": "string"
                }
            }
        },
        "github_com_rodrigocostarcs_pix-generator_internal_interfaces_api_views.Response": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Dados de resposta (opcional)"
                },
                "error": {
                    "description": "Mensagem de erro (apenas quando Success = false)\nexample: Credenciais inválidas",
                    "type": "string"
                },
                "success": {
                    "description": "Indica se a requisição foi bem-sucedida\nexample: true",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Digite 'Bearer ' seguido do token JWT",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Gerador de PIX API",
	Description:      "API para geração e gerenciamento de códigos PIX seguindo arquitetura DDD.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
